name: Publish ðŸ“¦ TestPyPI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  ci:
    name: Publish ðŸ“¦ Test PyPI
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: [1.2.2]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Publish distribution ðŸ“¦ to Test PyPI
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $TEST_PYPI_TOKEN
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --build
